### ISSUE TITLE
Add Student Recipe to Repository

### ISSUE THREAD

**Issue by joaedwar** [joaedwar/demonstration-example#1]
**Task:**  Create a procedure which details how to create a dish.

**Note:** You must create a new file after forking the repository and give the file a unique name that follows convention (e.g. proc_recipe-FIRSTNAME-LASTNAME).

Include the following: 
- Bulleted list of ingredients
- Overview of what it is needed and what is to be created
- Numbered steps for procedure
- Include at least one admonition

Use this [link](https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/) as a reference
Use this [link](https://github.com/finp/siteless/blob/master/TEMPLATE_PROCEDURE_doing-one-procedure.adoc) as a reference for creating a procedure module.

**Comment by ChloeMcHugh** [comment]
Added Borscht recipe.
